### ISSUE TITLE
Is typescript support on the horizon with this plugin?

### ISSUE THREAD

**Issue by j-d-carmichael** [cheap-glitch/vue-cli-plugin-sitemap#22] opened 2021-10-16 14:47 UTC
As the title says really.. I have a vue app in typescript but adding this plugin fails as it cannot parse ts. 

Adding ts-node at the top half works but then it cannot resolve the .vue files properly :/

```
require('ts-node').register();
const routes = require('./src/router/routes.ts');
```

**Comment by cheap-glitch** [comment] 2021-10-19 18:14
Yes, TypeScript support is planned. I don't use Vue CLI anymore so I've been putting it off for a while now, but I intend to release a new version in the coming weeks or months.

Closing as duplicate of #16

**Closed as completed by cheap-glitch** 2021-10-19 18:14 UTC
Labels: duplicate
