### ISSUE TITLE
Doesn't support typescript

### ISSUE THREAD

**Issue by dorklein** [cheap-glitch/vue-cli-plugin-sitemap#16] opened 2020-12-16 14:18 UTC
When the routes array is in a typescript module (routes.ts) with typescript specific syntax, then we can't import it into vue.config.js.

### When I write:
```javascript
require = require('esm')(module)
const routes = require('./src/router/routes/index.ts')
```

### I get the error:
```
 SyntaxError: Invalid or unexpected token
.../src/router/routes/index.ts:11
export default <RouteConfig[]>[
                         ^

```

**Comment by sneko** [comment] 2021-09-15 08:19
@dorklein did you find a workaround? Seems really annoying for TypeScript projects... I won't make a duplicate of my routes just to generate a sitemap 😶

**Comment by dontwan** [comment] 2022-02-08 11:33
We are running into the same problem.
Any progress on Typescript support?

**Comment by nexorianus** [comment] 2022-08-02 11:43
pushing this again.
Vue2 with TS inside the routes (or better within the slug generation code) - even serving wont work, because of JS.TS problems.

**Comment by steven87vt** [comment] 2023-05-26 23:53
What i did was write routes.js, then import it using require into vue.config.js and process it using helper modules to add my dynamic configuration.

```js
//routes.js
const viewOption = {
  NavBar: () => import(/* webpackChunkName: "nav" */ '../nav/Nav.vue'),
  HomeView: () => import(/* webpackChunkName: "home" */ '../views/HomeView.vue'),
}

/**
 * Populates routes with corresponding views using lazy loading strategy.
 * @param {import('vue-router').RouteRecordRaw[]} routes
 * @returns {import('vue-router').RouteRecordRaw[]}
 */
const configureRoutes = (routes) => {
routes.map((x) => {
    const children = x.children == null ? undefined : configureRoutes(x.children)
    const component = x.component == null ? undefined : viewOption[x.component.name]
    const components =
      x.components == null
        ? undefined
        : Object.keys(x.components).reduce((p, key) => {
            if (p[key]) {
              return p
            }

            p[key] = viewOption[x.components[key]]
            return p
          }, {})

    return {
      ...x,
      children,
      component,
      components
    }
  })
```

Then you can drive the routes via configuration or some other means. In my case I made interfaces friendly for configuration and created a schema for it based on my needs.

`// config.json`
```json
{
  "$schema": "../schemas/config.schema.json",
  "routes": [
    {
      "path": "/",
      "name": "homeView",
      "components": {  "default": "HomeView", "NavBar":  "NavBar"  },
    }
  ]
}
```

Set your `tsconfig.json` settings to allow `.js` and `.json`, I'm using ESNext target:

```json
"allowJs": true,
"resolveJsonModule": true,
"esModuleInterop": true <--- might not need this one for your use case
```

Drive your site map system from webpack or in my case vue CLI's webpack config wrapper. The process would be native ES imports in rollup I believe.

```js
// vue.config.js

const webpack = require('webpack')
const path = require('path')
const routes = require('./src/router/routes.js')

const _configuration = require('./src/config.json') // imports json file from above

// process dynamic configuration between named lazy imports and json configuration + remove unwanted paths/routes 
const siteMapRoutes = routes.configureRoutes(_configuration.routes).filter((x) => !x.path.startsWith('/index') || x.name !== 'notFound')

const sitemap = {
  baseURL: 'https://ezwebproductions.com', //<~ free plug, hope the example helped.
  routes: siteMapRoutes,
  defaults: {
    lastmod: new Date()
  }
}
```

**Closed as completed** 2023-12-09 14:32 UTC
Labels: enhancement
